### ISSUE TITLE
/var/lib/letsencrypt/checked file blocks LE updates

### ISSUE THREAD

**Issue by sunweaver** [D0n1elT/setup-letsencrypt#13]
@D0n1elT By @Ionic code was added to the letsencrypt-renew-cert script that creates a checked file in /var/lib/letsencrypt/. If the file exists, then LE updates are skipped.

This causes LE updates on several servers in our company. Can you (as paid work time) investigate this and find out why the checked file is created in the first place and why it is not cleanup properly at the end of a script run.

(Maybe it needs a signal trap here to do a proper cleanup after a script failure).

Thanks!

**Comment by Ionic** [comment]
I can probably help with that.

The `checked` file is there to prevent the script from renewing one (or multiple) certificates if that already successfully happened during the current month - I use a modified script on my personal machine for multiple certs.

It is:
  - created at the very end of the renewal run in case everything went fine (see `set -e`, which is supposed to skip the creation of the file automatically if errors occurred)
  - removed at the beginning of the script if it exists and if the script is being executed on the **first day of the month**, which means that the cron job must be executed at least once every seven days and at least once on the first day of the month - e.g., `0 0 */7 * * /path/to/letsencrypt-renew-certs...` would do the trick
---
There's also a bug (see #15) with the intermediate cert handling on ymir, since I haven't backported the changes from japsand - ACMEv2 is returning certificates with the intermediate already included, so we don't have to and must not concatenate things any longer. Will fix that up shortly.
